"""Persist routing memory and deterministic message order.

Revision ID: 0003
Revises: 0002
"""
import sqlalchemy as sa
from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("conversations", sa.Column("capture_asks", sa.Integer(), nullable=False, server_default="0"))
    op.add_column("conversations", sa.Column("qualify_asked", sa.JSON(), nullable=False, server_default="[]"))
    op.add_column("conversations", sa.Column("last_step", sa.String(20), nullable=False, server_default=""))
    # Backfill old pairs with visitor before assistant at equal timestamps.
    op.add_column("messages", sa.Column("sequence", sa.BigInteger()))
    op.execute("WITH ordered AS (SELECT id, row_number() OVER (ORDER BY created_at, "
               "CASE WHEN role = 'user' THEN 0 ELSE 1 END, id) AS n FROM messages) "
               "UPDATE messages SET sequence = ordered.n FROM ordered WHERE messages.id = ordered.id")
    op.alter_column("messages", "sequence", nullable=False)
    op.execute("ALTER TABLE messages ALTER COLUMN sequence ADD GENERATED BY DEFAULT AS IDENTITY")
    op.execute("SELECT setval(pg_get_serial_sequence('messages', 'sequence'), "
               "COALESCE((SELECT max(sequence) FROM messages), 0) + 1, false)")
    op.create_unique_constraint("uq_messages_sequence", "messages", ["sequence"])


def downgrade() -> None:
    op.drop_constraint("uq_messages_sequence", "messages", type_="unique")
    op.drop_column("messages", "sequence")
    for name in ("last_step", "qualify_asked", "capture_asks"):
        op.drop_column("conversations", name)
